import {
  Sparkles, Bot, Hash, BarChart2, FileText, Link2, Zap,
  RefreshCw, Clock, Target, Layers, MessageSquare, Newspaper,
  Video, Presentation, TrendingUp, Trophy, Eye, Calendar,
  Mail, Bell, Users, Settings, Shield, Search
} from "lucide-react";

// ── Data (English) ───────────────────────────────────────────────────────────
export const SECTIONS_EN = [
  {
    id: "post-generation",
    icon: <Sparkles size={15} />,
    color: "text-linkedin bg-linkedin/10 border-linkedin/20",
    title: "Post Generation",
    subtitle: "Create daily LinkedIn posts using AI",
    features: [
      {
        name: "AI Post Generator",
        icon: <Bot size={13} />,
        what: "Automatically generates daily LinkedIn posts using Gemini 2.5 Flash AI. Rotates topics daily — Monday: Career, Tuesday: Tech, Wednesday: Project, Thursday: Coding Tip, Friday: Web3, Saturday: Tools, Sunday: Motivation.",
        how: "A post is automatically generated for today when the home page loads. You can regenerate it using the 'Regenerate' button, or create a custom post by typing your topic in the custom prompt box.",
        tip: "Be sure to 'Humanize' after generating a post to avoid LinkedIn's AI-detection penalty (-30% reach).",
      },
      {
        name: "AI Humanizer",
        icon: <Sparkles size={13} />,
        what: "Runs an additional AI pass on the generated post to inject your project names, personal metrics (e.g., 15k users, 60% latency), and a casual tone so it doesn't look AI-written.",
        how: "Click the 'Humanize' button on the post card. The post automatically updates with the changes.",
        tip: "LinkedIn's Nexus algorithm imposes a -30% reach and -55% engagement penalty on AI content. The Humanizer eliminates this risk.",
      },
      {
        name: "Hook Generator",
        icon: <Hash size={13} />,
        what: "Generates 3 alternate opening lines for a single post. The first 2 lines are the most critical on LinkedIn—they decide whether people click 'see more'.",
        how: "Click the 'Hooks' button on the post card. Select the best option to automatically replace the first paragraph.",
        tip: "Hooks driven by curiosity or surprise yield the highest click-through rate.",
      },
      {
        name: "Depth Score Card",
        icon: <BarChart2 size={13} />,
        what: "Calculates the Depth Score (0-100), which is the primary ranking signal of the LinkedIn 2026 Nexus algorithm based on dwell time, comment quality, saves, and shares.",
        how: "Displays automatically at the bottom of the post card. Green = high, Yellow = medium, Red = low. Follow the suggestions to improve your score.",
        tip: "Posts with 1500+ characters, numbered lists, and an open question at the end increase the score the most.",
      },
      {
        name: "Post Editor",
        icon: <FileText size={13} />,
        what: "Allows manual editing of both content and hashtags after generation.",
        how: "Click the pencil (edit) icon on the post card. Make changes in the modal and save.",
        tip: "The Depth Score automatically recalculates after editing the post.",
      },
    ],
  },
  {
    id: "publishing",
    icon: <Link2 size={15} />,
    color: "text-blue-600 bg-blue-50 border-blue-200",
    title: "Publishing & LinkedIn",
    subtitle: "One-click publishing to LinkedIn",
    features: [
      {
        name: "LinkedIn OAuth Connect",
        icon: <Link2 size={13} />,
        what: "Allows connection to your LinkedIn account. Once connected, publish posts directly in a single click.",
        how: "Click 'Connect LinkedIn' in the left sidebar. Log in on the LinkedIn authorization page. You'll be redirected back. The token is valid for 60 days.",
        tip: "The app displays a reminder before the token expires. Reconnecting takes less than a minute.",
      },
      {
        name: "One-Click Post to LinkedIn",
        icon: <Zap size={13} />,
        what: "Publishes directly from the post card to LinkedIn with text and an AI-generated image.",
        how: "Click 'Post to LinkedIn' on the post card. If connected, it publishes instantly. Otherwise, a pre-filled LinkedIn compose window opens.",
        tip: "The Golden Hour timer starts automatically after posting.",
      },
      {
        name: "LinkedIn Stats Auto-Sync",
        icon: <RefreshCw size={13} />,
        what: "Automatically pulls reactions and comments of published posts via LinkedIn API. Free tier retrieves likes and comments.",
        how: "Go to Growth Dashboard → Analytics tab → Click 'Sync Now'. It also syncs automatically in the background 90 minutes and 24 hours after posting.",
        tip: "Impressions/views must be logged manually from LinkedIn Analytics.",
      },
    ],
  },
  {
    id: "algorithm",
    icon: <TrendingUp size={15} />,
    color: "text-emerald-600 bg-emerald-50 border-emerald-200",
    title: "Algorithm Tools",
    subtitle: "Understand and leverage the LinkedIn algorithm",
    features: [
      {
        name: "Golden Hour Timer",
        icon: <Clock size={13} />,
        what: "Activates a 90-minute countdown timer after publishing. LinkedIn shows your post to an initial 2-5% of your network—strong engagement here leads to wider distribution.",
        how: "Appears automatically on screen after posting. Follow milestones: reply to the first comment at T+0 min, add a follow-up at T+30 min, start a thread at T+60 min.",
        tip: "Author replies within 30 min result in 64% more comments and 2.3x more views.",
      },
      {
        name: "Topic DNA Tracker",
        icon: <Target size={13} />,
        what: "Tracks topics posted in the last 30 days and shows authority levels: None / Weak / Emerging / Growing / Expert.",
        how: "Appears automatically in the right sidebar. Shows a warning if a topic has been missed for 14+ days.",
        tip: "Posting consistently on a topic signals expert authority to LinkedIn, granting more distribution in that niche.",
      },
      {
        name: "Format Rotation",
        icon: <Layers size={13} />,
        what: "Automatically rotates post formats (text, carousel, poll). Posting the same format on consecutive days suppresses reach by 20%.",
        how: "Works automatically in the background. The format is decided during post generation.",
        tip: "A follower CTA is added automatically every 7th post—followers yield 25-30% reach vs 10-15% for connections.",
      },
      {
        name: "Comment Seeding Panel",
        icon: <MessageSquare size={13} />,
        what: "Generates DM templates for 5 trusted connections before publishing. Early comments signal post value to the algorithm.",
        how: "Open via the 'Seed' button on the post card or from the sidebar. Add your connections list once to get personalized DM templates for each post.",
        tip: "Unlike engagement pods (which risk shadowbans), this is a genuine early signal.",
      },
    ],
  },
  {
    id: "content-tools",
    icon: <FileText size={15} />,
    color: "text-violet-600 bg-violet-50 border-violet-200",
    title: "Content Tools",
    subtitle: "Turn posts into multiple content formats",
    features: [
      {
        name: "PDF Carousel Generator",
        icon: <Layers size={13} />,
        what: "Creates a 5-8 slide LinkedIn PDF carousel from any topic or post. PDF carousels get a 6.6% average engagement rate vs 2% for plain text.",
        how: "Go to Left Sidebar → 'Carousel Generator'. Select a topic or existing post, generate slides, preview, and download the PDF to upload as a document on LinkedIn.",
        tip: "Optimal vertical format of 1080×1350px. Branded slides automatically display your name.",
      },
      {
        name: "Newsletter Generator",
        icon: <Newspaper size={13} />,
        what: "Generates a complete LinkedIn newsletter edition (title, intro, body, insights, CTA) from your best post of the week.",
        how: "Open from Growth Dashboard → 'Newsletter' or the sidebar. Select the week's best post, generate content, and paste it into a LinkedIn article.",
        tip: "LinkedIn newsletters bypass the feed and go directly to inboxes (25-35% open rates vs 2% feed reach).",
      },
      {
        name: "Video Script Generator",
        icon: <Video size={13} />,
        what: "Creates a 30-60 second vertical video script from any post or topic, including scenes, spoken text, visuals, and tips.",
        how: "Open via the video icon on the post card or sidebar, enter a topic, and generate the script.",
        tip: "Short video format gets 5x more engagement on LinkedIn. Once the script is ready, just record!",
      },
      {
        name: "Presentation Generator",
        icon: <Presentation size={13} />,
        what: "Generates a complete slide deck from a post or topic using Gemini content, featuring 4 themes and exporting to .pptx.",
        how: "Go to Left Sidebar → 'Presentation Generator', select topic/post, choose theme, generate, and download.",
        tip: "AI images are automatically generated for each slide using Pollinations.ai.",
      },
      {
        name: "Twitter Thread Panel",
        icon: <Hash size={13} />,
        what: "Converts LinkedIn posts to Twitter/X threads with tweet-by-tweet previews, character counts, and per-tweet images.",
        how: "Click the Twitter icon on the post card, preview the thread, copy it, or open Twitter directly.",
        tip: "Same content, second platform — zero extra effort.",
      },
      {
        name: "Strategic Comment Generator",
        icon: <MessageSquare size={13} />,
        what: "Generates thoughtful 2-3 sentence comments for posts by industry leaders (e.g., Dan Abramov, Lee Robinson) or custom URLs. Comments on viral posts can fetch 10K+ impressions.",
        how: "Growth Dashboard → 'Strategic Comments'. Enter post URL, generate, review, and paste on LinkedIn.",
        tip: "Strategic commenting on relevant posts grows organic followers safely without shadowban risks.",
      },
    ],
  },
  {
    id: "trending",
    icon: <TrendingUp size={15} />,
    color: "text-orange-600 bg-orange-50 border-orange-200",
    title: "Trending Scanner",
    subtitle: "Write about hot developer topics at the perfect time",
    features: [
      {
        name: "Trending Tech Scanner",
        icon: <TrendingUp size={13} />,
        what: "Scans 4 daily sources (GitHub Trending, Hacker News, dev.to, npm weekly) to identify trending developer topics.",
        how: "Click 'Trending' in the top nav for the full page, or use the TrendingPanel in the sidebar. Click 'Generate Post' on any item.",
        tip: "Posting early on breaking news yields maximum reach. The algorithm boosts posts matching trending topics.",
      },
      {
        name: "Trending Panel (Sidebar)",
        icon: <TrendingUp size={13} />,
        what: "Shows the top 3 relevant trending items in the right sidebar for quick access.",
        how: "Appears automatically in the right sidebar. Click 'Generate post' to create a post instantly.",
        tip: "A daily cron job runs at 7 AM IST to keep scanning data fresh.",
      },
    ],
  },
  {
    id: "growth",
    icon: <Trophy size={15} />,
    color: "text-amber-600 bg-amber-50 border-amber-200",
    title: "Growth Dashboard",
    subtitle: "Track progress and visualize ROI",
    features: [
      {
        name: "Streak Tracker",
        icon: <Trophy size={13} />,
        what: "Tracks consecutive posting days. 7 days builds algorithm authority; 30 days yields top 1% creator status.",
        how: "Growth Dashboard → Overview tab. The streak increases as long as you publish daily.",
        tip: "An email alert is sent at 7:30 PM IST if you are at risk of breaking your streak.",
      },
      {
        name: "Analytics & Best Posts",
        icon: <BarChart2 size={13} />,
        what: "Log engagement metrics (likes, comments, shares, views, clicks) to identify best performing topics.",
        how: "Growth Dashboard → Analytics / Best Posts tab. Click 'Log' and paste numbers from LinkedIn Analytics.",
        tip: "Logging helps the Evergreen Recycler identify candidates for recycling.",
      },
      {
        name: "Evergreen Post Recycler",
        icon: <RefreshCw size={13} />,
        what: "Identifies high-performing posts older than 90 days and suggests reposting them with a fresh hook.",
        how: "Growth Dashboard → Evergreen tab. Click 'Refresh & Repost' to generate a new hook with Gemini.",
        tip: "Most of your current followers haven't seen your old posts, making recycling highly effective.",
      },
      {
        name: "Opportunity Tracker",
        icon: <Target size={13} />,
        what: "Logs results from posting (recruiter DMs, freelance inquiries, speaking invites, follower milestones).",
        how: "Click 'Opportunity Tracker' in the sidebar and enter opportunity details.",
        tip: "Serves as a motivation engine by making tangible ROI visible even during slow weeks.",
      },
      {
        name: "Profile Visitor Tracker",
        icon: <Eye size={13} />,
        what: "Logs weekly profile views and displays week-over-week growth percentage and spark charts.",
        how: "Growth Dashboard → Profile Visits. Copy weekly views from LinkedIn Analytics and log them.",
        tip: "Visualizes the direct correlation between posting consistency and profile views.",
      },
      {
        name: "Content Calendar",
        icon: <Calendar size={15} />,
        what: "Plan topics, formats, and custom prompts up to 7 days in advance.",
        how: "Growth Dashboard → Content Calendar. Click a day, override the topic/format, and click 'Generate'.",
        tip: "Plan on weekends to put your weekday execution on autopilot.",
      },
    ],
  },
  {
    id: "reminders",
    icon: <Bell size={15} />,
    color: "text-rose-600 bg-rose-50 border-rose-200",
    title: "Reminders & Alerts",
    subtitle: "Never miss a posting opportunity",
    features: [
      {
        name: "Daily Email Reminder",
        icon: <Mail size={13} />,
        what: "Sends an email at the optimal posting time containing a post preview and a direct link, powered by a cron job.",
        how: "Settings → Enter email, set reminder time, and verify your email once.",
        tip: "Tuesday–Thursday 8–9 AM IST is the peak reach window.",
      },
      {
        name: "Streak Alert",
        icon: <Bell size={13} />,
        what: "Checks at 7:30 PM IST and sends an email if you haven't posted yet today.",
        how: "Runs automatically when reminders are enabled and your streak is active.",
        tip: "The email indicator changes to red when only 2 hours remain.",
      },
      {
        name: "Push Notifications",
        icon: <Bell size={13} />,
        what: "Browser notifications for trending topics, published posts, and streak alerts.",
        how: "Settings → Enable Push Notifications and grant browser permissions.",
        tip: "Enable both email and push notifications for reliable reminders.",
      },
      {
        name: "In-App Notifications",
        icon: <Bell size={13} />,
        what: "A notification bell in the top nav showing recent activities, persisted to the database.",
        how: "Click the bell icon or view history with filters on the notifications page.",
        tip: "Real-time updates are pushed via SSE (Server-Sent Events).",
      },
    ],
  },
  {
    id: "profile",
    icon: <Users size={15} />,
    color: "text-sky-600 bg-sky-50 border-sky-200",
    title: "Profile & SEO",
    subtitle: "Optimize profile visibility for recruiters",
    features: [
      {
        name: "LinkedIn Profile SEO Auditor",
        icon: <Search size={13} />,
        what: "Audits headlines, about sections, and skills according to 2026 recruiter search patterns to generate optimized versions.",
        how: "Left sidebar → 'Profile SEO Auditor'. Paste details and run the audit.",
        tip: "Optimized profiles receive up to 40% more views and 36x more recruiter messages.",
      },
      {
        name: "Edit Profile",
        icon: <Settings size={13} />,
        what: "Updates your developer profile in the app, serving as the basis for AI post generation.",
        how: "Click 'Edit' on the profile card in the left sidebar and fill in details.",
        tip: "Add all technologies to your stack so Gemini can incorporate them into posts.",
      },
    ],
  },
  {
    id: "settings",
    icon: <Settings size={15} />,
    color: "text-gray-600 bg-gray-50 border-gray-200",
    title: "Settings & Account",
    subtitle: "Configure the application to your preferences",
    features: [
      {
        name: "Settings Panel",
        icon: <Settings size={13} />,
        what: "Configure reminder times, email details, push notifications, and topic filters.",
        how: "Click the settings icon in the top nav or the link in the right sidebar.",
        tip: "Topic filters customize what the trending tech scanner tracks (e.g., React, Node, Web3, DevOps).",
      },
      {
        name: "Pro Upgrade (Razorpay)",
        icon: <Shield size={13} />,
        what: "Unlocks unlimited posts (free tier has a limit of 5 posts per day) and premium features.",
        how: "Click 'Upgrade' in the top nav or trigger a limit check to open the Razorpay checkout.",
        tip: "Set NEXT_PUBLIC_ENABLE_MONETIZATION=true in your .env file to enable monetization.",
      },
    ],
  },
];

// ── Data (Hindi) ─────────────────────────────────────────────────────────────
export const SECTIONS_HI = [
  {
    id: "post-generation",
    icon: <Sparkles size={15} />,
    color: "text-linkedin bg-linkedin/10 border-linkedin/20",
    title: "पोस्ट जनरेशन",
    subtitle: "एआई (AI) की मदद से रोज़ाना लिंक्डइन पोस्ट्स बनाना",
    features: [
      {
        name: "एआई पोस्ट जनरेटर",
        icon: <Bot size={13} />,
        what: "Gemini 2.5 Flash एआई का उपयोग करके रोज़ाना लिंक्डइन पोस्ट बनाता है। यह स्वचालित रूप से हर दिन विषय बदलता है - सोमवार: करियर, मंगलवार: टेक, बुधवार: प्रोजेक्ट, गुरुवार: कोडिंग टिप्स, शुक्रवार: वेब3, शनिवार: टूल्स, रविवार: मोटिवेशन।",
        how: "होम पेज लोड होने पर आज की पोस्ट स्वचालित रूप से बन जाती है। आप 'Regenerate' बटन का उपयोग करके इसे फिर से बना सकते हैं, या कस्टम प्रॉम्प्ट बॉक्स में अपना विषय लिखकर कस्टम पोस्ट बना सकते हैं।",
        tip: "पोस्ट जेनरेट करने के बाद 'Humanize' ज़रूर करें ताकि लिंक्डइन के एआई-डिटेक्शन पेनल्टी (-30% रीच) से बचा जा सके।",
      },
      {
        name: "एआई ह्यूमनाइज़र",
        icon: <Sparkles size={13} />,
        what: "जेनरेट की गई पोस्ट पर एक अतिरिक्त एआई पास चलाता है जो आपके प्रोजेक्ट्स के नाम, व्यक्तिगत मैट्रिक्स (जैसे 15k यूज़र्स, 60% लेटेंसी), और अनौपचारिक भाषा को जोड़ता है ताकि पोस्ट एआई-लिखित न लगे।",
        how: "पोस्ट कार्ड पर 'Humanize' बटन पर क्लिक करें। पोस्ट स्वचालित रूप से परिवर्तनों के साथ अपडेट हो जाती है।",
        tip: "लिंक्डइन का नेक्सस एल्गोरिदम एआई कंटेंट पर -30% रीच और -55% एंगेजमेंट पेनल्टी लगाता है। ह्यूमनाइज़र इस जोखिम को समाप्त करता है।",
      },
      {
        name: "हुक जनरेटर",
        icon: <Hash size={13} />,
        what: "एक ही पोस्ट के लिए 3 वैकल्पिक शुरुआती पंक्तियाँ जेनरेट करता है। लिंक्डइन पर पहली 2 पंक्तियाँ सबसे महत्वपूर्ण होती हैं — यही तय करती हैं कि लोग 'see more' पर क्लिक करें या नहीं।",
        how: "पोस्ट कार्ड पर 'Hooks' बटन पर क्लिक करें। तीन विकल्पों में से सर्वश्रेष्ठ पर क्लिक करें — पोस्ट का पहला पैराग्राफ स्वचालित रूप से बदल जाता है।",
        tip: "जिज्ञासा या आश्चर्य पैदा करने वाले हुक सबसे अधिक क्लिक लाते हैं।",
      },
      {
        name: "डेप्थ स्कोर कार्ड",
        icon: <BarChart2 size={13} />,
        what: "डेप्थ स्कोर (0-100) की गणना करता है, जो लिंक्डइन 2026 नेक्सस एल्गोरिदम का मुख्य रैंकिंग सिग्नल है — ड्वेल टाइम (dwell time), कमेंट क्वालिटी, सेव और शेयर पर आधारित।",
        how: "यह पोस्ट कार्ड के नीचे स्वचालित रूप से दिखाई देता है। हरा = उच्च, पीला = मध्यम, लाल = कम। अपना स्कोर सुधारने के लिए दिए गए सुझावों का पालन करें।",
        tip: "1500+ अक्षरों वाली पोस्ट, नंबर वाली सूचियाँ और अंत में एक खुला प्रश्न स्कोर को सबसे अधिक बढ़ाते हैं।",
      },
      {
        name: "पोस्ट एडिटर",
        icon: <FileText size={13} />,
        what: "पोस्ट जेनरेट होने के बाद उसे मैन्युअल रूप से संपादित करने (कंटेंट और हैशटैग दोनों) की अनुमति देता है।",
        how: "पोस्ट कार्ड पर पेंसिल (संपादित करें) आइकन पर क्लिक करें। मोडल में बदलाव करें और सहेजें (Save)।",
        tip: "पोस्ट को संपादित करने के बाद डेप्थ स्कोर स्वचालित रूप से पुनः परिकलित हो जाता है।",
      },
    ],
  },
  {
    id: "publishing",
    icon: <Link2 size={15} />,
    color: "text-blue-600 bg-blue-50 border-blue-200",
    title: "पब्लिशिंग और लिंक्डइन",
    subtitle: "एक क्लिक में लिंक्डइन पर पोस्ट करें",
    features: [
      {
        name: "लिंक्डइन OAuth कनेक्ट",
        icon: <Link2 size={13} />,
        what: "आपको अपने लिंक्डइन खाते से कनेक्ट करने की अनुमति देता है। एक बार कनेक्ट होने के बाद, आप सीधे एक क्लिक में पोस्ट पब्लिश कर सकते हैं।",
        how: "बायें साइडबार में 'Connect LinkedIn' बटन पर क्लिक करें। लिंक्डइन लॉगिन पेज खुलेगा। अधिकृत (Authorize) करें — आप वापस ऐप पर आ जाएंगे। टोकन 60 दिनों तक वैध रहता है।",
        tip: "टोकन समाप्त होने से पहले ऐप रिमाइंडर दिखाता है। दोबारा कनेक्ट करना 1 मिनट से भी कम समय का काम है।",
      },
      {
        name: "वन-क्लिक लिंक्डइन पोस्ट",
        icon: <Zap size={13} />,
        what: "पोस्ट कार्ड से सीधे लिंक्डइन पर पब्लिश करता है — टेक्स्ट और एआई-जेनरेटेड इमेज के साथ।",
        how: "पोस्ट कार्ड पर 'Post to LinkedIn' बटन पर क्लिक करें। यदि लिंक्डइन कनेक्टेड है, तो तुरंत पब्लिश हो जाएगा। अन्यथा, एक पूर्व-भरे (pre-filled) विवरण के साथ लिंक्डइन कंपोज़ विंडो खुलेगी।",
        tip: "पोस्ट करने के बाद गोल्डन आवर टाइमर स्वचालित रूप से शुरू हो जाता है।",
      },
      {
        name: "लिंक्डइन आँकड़े ऑटो-सिंक",
        icon: <RefreshCw size={13} />,
        what: "पब्लिश की गई पोस्ट के रिएक्शन्स और कमेंट्स को लिंक्डइन एपीआई से ऑटो-सिंक करता है। फ्री टियर में लाइक्स और कमेंट्स मिलते हैं।",
        how: "ग्रोथ डैशबोर्ड → एंगेजमेंट टैब → 'Sync Now' बटन। या स्वचालित रूप से — पोस्ट करने के 90 मिनट और 24 घंटे बाद बैकग्राउंड में सिंक होता है।",
        tip: "इम्प्रेशन/व्यूज को लिंक्डइन एनालिटिक्स से मैन्युअल रूप से लॉग करना पड़ता है।",
      },
    ],
  },
  {
    id: "algorithm",
    icon: <TrendingUp size={15} />,
    color: "text-emerald-600 bg-emerald-50 border-emerald-200",
    title: "एल्गोरिदम टूल्स",
    subtitle: "लिंक्डइन के एल्गोरिदम को समझें और उपयोग करें",
    features: [
      {
        name: "गोल्डन आवर टाइमर",
        icon: <Clock size={13} />,
        what: "पोस्ट पब्लिश होने के बाद 90-मिनट का काउंटडाउन टाइमर सक्रिय होता है। लिंक्डइन शुरुआत में आपके 2-5% नेटवर्क को पोस्ट दिखाता है — यदि उनका एंगेजमेंट मजबूत हो तो अधिक डिस्ट्रीब्यूशन मिलता है।",
        how: "पोस्ट करने के बाद यह स्क्रीन पर स्वचालित रूप से आ जाता है। माइलस्टोन्स का पालन करें: T+0 मिनट पर पहले कमेंट का जवाब दें, T+30 मिनट पर फॉलो-अप जोड़ें, T+60 मिनट पर थ्रेड स्टार्टर।",
        tip: "30 मिनट के भीतर लेखक के जवाब = 64% अधिक कमेंट्स और 2.3 गुना अधिक व्यूज मिलते हैं।",
      },
      {
        name: "टॉपिक DNA ट्रैकर",
        icon: <Target size={13} />,
        what: "पिछले 30 दिनों में आपने किन विषयों पर कितने पोस्ट किए, इसे ट्रैक करता है। अथॉरिटी स्तर दिखाता है: कोई नहीं / कमजोर / उभरता हुआ / बढ़ रहा है / विशेषज्ञ।",
        how: "दाएँ साइडबार में स्वचालित रूप से दिखाई देता है। यदि 14+ दिनों से कोई विषय छूट गया है तो चेतावनी दिखाता है।",
        tip: "किसी विषय पर लगातार पोस्ट करने को लिंक्डइन विशेषज्ञ अथॉरिटी मानता है और उस श्रेणी में अधिक रीच देता है।",
      },
      {
        name: "फॉर्मेट रोटेशन",
        icon: <Layers size={13} />,
        what: "स्वचालित रूप से पोस्ट फॉर्मेट बदलता है — टेक्स्ट, कैरोसेल, पोल। लगातार दिनों में एक ही फॉर्मेट का उपयोग करने से 20% रीच कम हो जाती है।",
        how: "बैकग्राउंड में स्वचालित रूप से काम करता है। हर पोस्ट जेनरेट होते समय उसका फॉर्मेट तय होता है।",
        tip: "हर 7वीं पोस्ट में फॉलोअर CTA स्वचालित रूप से जुड़ जाता है — फॉलोअर्स से 25–30% रीच मिलती है बनाम कनेक्शंस से 10–15%।",
      },
      {
        name: "कमेंट सीडिंग पैनल",
        icon: <MessageSquare size={13} />,
        what: "पोस्ट पब्लिश करने से पहले 5 भरोसेमंद कनेक्शंस को भेजने के लिए डीएम (DM) टेम्पलेट बनाता है। उनके शुरुआती कमेंट्स एल्गोरिदम को संकेत देते हैं कि पोस्ट मूल्यवान है।",
        how: "पोस्ट कार्ड पर 'Seed' बटन या साइडबार से खोलें। कनेक्शंस सूची को एक बार जोड़ें, फिर हर पोस्ट के लिए व्यक्तिगत डीएम टेम्पलेट प्राप्त करें।",
        tip: "यह एंगेजमेंट पॉड्स (जो शैडोबैन का जोखिम लाती हैं) से अलग है। यह एक वास्तविक प्रारंभिक एंगेजमेंट सिग्नल है।",
      },
    ],
  },
  {
    id: "content-tools",
    icon: <FileText size={15} />,
    color: "text-violet-600 bg-violet-50 border-violet-200",
    title: "कंटेंट टूल्स",
    subtitle: "एक पोस्ट से कई तरह का कंटेंट बनाना",
    features: [
      {
        name: "पीडीएफ कैरोसेल जनरेटर",
        icon: <Layers size={13} />,
        what: "किसी भी विषय या पोस्ट से 5-8 स्लाइड का लिंक्डइन पीडीएफ कैरोसेल बनाता है। पीडीएफ कैरोसेल का औसत एंगेजमेंट रेट 6.6% है बनाम प्लेन टेक्स्ट का 2%।",
        how: "बायें साइडबार → 'Carousel Generator' पर जाएं। विषय या मौजूदा पोस्ट चुनें, स्लाइड्स जेनरेट करें, प्रीव्यू देखें और पीडीएफ डाउनलोड करें। फिर इसे लिंक्डइन पर पोस्ट करें।",
        tip: "1080×1350px वर्टिकल फॉर्मेट — लिंक्डइन के लिए सर्वोत्तम है। ब्रांडेड स्लाइड्स में आपका नाम ऑटोमैटिक आता है।",
      },
      {
        name: "न्यूज़लेटर जनरेटर",
        icon: <Newspaper size={13} />,
        what: "सप्ताह के सबसे बेहतरीन पोस्ट से एक संपूर्ण लिंक्डइन न्यूज़लेटर संस्करण (शीर्षक, परिचय, मुख्य भाग, इनसाइट्स, CTA) जेनरेट करता है।",
        how: "ग्रोथ डैशबोर्ड → 'Newsletter' या साइडबार से खोलें। सप्ताह का बेस्ट पोस्ट चुनें, जेनरेट करें, सेक्शन्स कॉपी करें और लिंक्डइन पर पेस्ट करें।",
        tip: "लिंक्डइन न्यूज़लेटर फ़ीड को बायपास करते हैं — सीधे इनबॉक्स में जाते हैं। 25-35% ओपन रेट मिलता है बनाम फ़ीड रीच का 2%।",
      },
      {
        name: "वीडियो स्क्रिप्ट जनरेटर",
        icon: <Video size={13} />,
        what: "किसी भी पोस्ट या विषय से 30-60 सेकंड का वर्टिकल वीडियो स्क्रिप्ट बनाता है — सीन-बाय-सीन ब्रेकडाउन, बोले जाने वाले टेक्स्ट और डिलीवरी टिप्स के साथ।",
        how: "पोस्ट कार्ड पर वीडियो आइकन या साइडबार से खोलें। विषय डालें, स्क्रिप्ट जेनरेट हो जाएगी।",
        tip: "शॉर्ट वीडियो फॉर्मेट लिंक्डइन पर 5 गुना अधिक एंगेजमेंट देता है। बस रिकॉर्ड करें!",
      },
      {
        name: "प्रेजेंटेशन जनरेटर",
        icon: <Presentation size={13} />,
        what: "पोस्ट या विषय से पूरी स्लाइड डेक बनाता है — जेमिनी सामग्री जेनरेट करता है, 4 थीम्स उपलब्ध हैं, और .pptx फ़ाइल निर्यात होती है।",
        how: "बायें साइडबार → 'Presentation Generator' पर जाएं। विषय/पोस्ट चुनें, थीम चुनें, जेनरेट करें और डाउनलोड करें।",
        tip: "Pollinations.ai से हर स्लाइड के लिए एआई इमेजेस अपने आप जेनरेट होती हैं।",
      },
      {
        name: "ट्विटर थ्रेड पैनल",
        icon: <Hash size={13} />,
        what: "लिंक्डइन पोस्ट को ट्विटर/X थ्रेड में बदलता है। ट्वीट-दर-ट्वीट प्रीव्यू, कैरेक्टर काउंट चेक और इमेज सपोर्ट करता है।",
        how: "पोस्ट कार्ड पर ट्विटर आइकन पर क्लिक करें। थ्रेड का प्रीव्यू देखें, कॉपी करें या सीधे ट्विटर पर पोस्ट करें।",
        tip: "एक ही कंटेंट, दूसरा प्लेटफॉर्म — बिना किसी अतिरिक्त प्रयास के।",
      },
      {
        name: "रणनीतिक कमेंट जनरेटर",
        icon: <MessageSquare size={13} />,
        what: "इंडस्ट्री लीडर्स (जैसे Dan Abramov, Lee Robinson) या कस्टम पोस्ट पर करने के लिए विचारशील 2-3 पंक्तियों के कमेंट्स बनाता है। वायरल पोस्ट पर कमेंट करने से 10K+ इम्प्रेशन मिल सकते हैं।",
        how: "ग्रोथ डैशबोर्ड → 'Strategic Comments'। पोस्ट का यूआरएल डालें, कमेंट्स जेनरेट करें और लिंक्डइन पर पेस्ट करें।",
        tip: "प्रासंगिक पोस्ट पर रणनीतिक कमेंट करने से बिना किसी शैडोबैन के रिस्क के ऑर्गेनिक फॉलोअर्स बढ़ते हैं।",
      },
    ],
  },
  {
    id: "trending",
    icon: <TrendingUp size={15} />,
    color: "text-orange-600 bg-orange-50 border-orange-200",
    title: "ट्रेंडिंग स्कैनर",
    subtitle: "डेवलपर विषयों पर सही समय पर पोस्ट करें",
    features: [
      {
        name: "ट्रेंडिंग टेक स्कैनर",
        icon: <TrendingUp size={13} />,
        what: "हर दिन 4 सोर्सेज को स्कैन करता है — GitHub Trending, Hacker News, dev.to, npm weekly — और प्रासंगिक डेवलपर विषय ढूंढता है।",
        how: "टॉप नेविगेशन बार में 'Trending' बटन पर क्लिक करें। या साइडबार में TrendingPanel से क्विक व्यू देखें। किसी भी आइटम पर 'Generate Post' पर क्लिक करें।",
        tip: "ब्रेकिंग न्यूज़ पर जल्दी पोस्ट करना = अधिकतम रीच। लिंक्डइन एल्गोरिदम ट्रेंडिंग टॉपिक्स पर पोस्ट को बूस्ट करता है।",
      },
      {
        name: "ट्रेंडिंग पैनल (साइडबार)",
        icon: <TrendingUp size={13} />,
        what: "क्विक एक्सेस के लिए दाएँ साइडबार में टॉप 3 प्रासंगिक ट्रेंडिंग टॉपिक्स दिखाता है।",
        how: "दाएँ साइडबार में ऑटोमैटिक दिखता है। 'Generate post' पर क्लिक करके तुरंत पोस्ट जेनरेट करें।",
        tip: "डेटा को ताज़ा रखने के लिए क्रॉन जॉब हर दिन सुबह 7 बजे (IST) स्कैन करता है।",
      },
    ],
  },
  {
    id: "growth",
    icon: <Trophy size={15} />,
    color: "text-amber-600 bg-amber-50 border-amber-200",
    title: "ग्रोथ डैशबोर्ड",
    subtitle: "प्रगति को ट्रैक करें, आरओआई (ROI) देखें",
    features: [
      {
        name: "स्ट्रिक ट्रैकर",
        icon: <Trophy size={13} />,
        what: "लगातार पोस्ट करने के दिनों (स्ट्रिक) को ट्रैक करता है। 7 दिन = एल्गोरिदम अथॉरिटी शुरू, 30 दिन = टॉप 1% क्रिएटर स्टेटस।",
        how: "ग्रोथ डैशबोर्ड → Overview टैब। जब तक आप रोज़ पोस्ट करते हैं, स्ट्रिक संख्या बढ़ती रहती है।",
        tip: "यदि स्ट्रिक टूटने वाली हो, तो शाम 7:30 बजे ईमेल अलर्ट आता है।",
      },
      {
        name: "एनालिटिक्स और बेस्ट पोस्ट्स",
        icon: <BarChart2 size={13} />,
        what: "हर पोस्ट के एंगेजमेंट को मैन्युअल रूप से लॉग कर सकते हैं — लाइक्स, कमेंट्स, शेयर्स, व्यूज। बेस्ट परफॉर्मिंग टॉपिक्स की पहचान होती है।",
        how: "ग्रोथ डैशबोर्ड → Analytics / Best Posts टैब। हर पोस्ट के लिए 'Log' पर क्लिक करें और लिंक्डइन एनालिटिक्स से नंबर भरें।",
        tip: "एक बार लॉग करने के बाद, एवरग्रीन रिसाइक्लर बेस्ट पोस्ट्स की पहचान आसानी से कर लेता है।",
      },
      {
        name: "एवरग्रीन पोस्ट रिसाइक्लर",
        icon: <RefreshCw size={13} />,
        what: "90+ दिन पुरानी हाई-एंगेजमेंट पोस्ट्स की पहचान करता है और नए हुक के साथ दोबारा पोस्ट करने का सुझाव देता है।",
        how: "ग्रोथ डैशबोर्ड → Evergreen टैब। 'Refresh & Repost' पर क्लिक करें — जेमिनी नया हुक जेनरेट करेगा।",
        tip: "आपके 60% फॉलोअर्स ने वह पुरानी पोस्ट नहीं देखी होगी, इसलिए रिसाइक्लिंग बहुत प्रभावी है।",
      },
      {
        name: "ऑपर्चुनिटी ट्रैकर",
        icon: <Target size={13} />,
        what: "पोस्टिंग से मिलने वाले परिणामों (रिक्रूटर डीएम, फ्रीलांस प्रोजेक्ट, कोलैबोरेशन, आदि) को ट्रैक करता है।",
        how: "साइडबार में 'Opportunity Tracker' पर क्लिक करें। अवसर का प्रकार और नोट जोड़ें।",
        tip: "यह एक मोटिवेशन इंजन की तरह काम करता है — कम व्यूज वाले हफ्तों में भी वास्तविक मूल्य दिखाता है।",
      },
      {
        name: "प्रोफ़ाइल विजिटर ट्रैकर",
        icon: <Eye size={13} />,
        what: "वीकली प्रोफ़ाइल व्यूज को लॉग करता है और सप्ताह-दर-सप्ताह विकास (%) दिखाता है।",
        how: "ग्रोथ डैशबोर्ड → Profile Visits। लिंक्डइन एनालिटिक्स से साप्ताहिक व्यूज लॉग करें।",
        tip: "प्रोफ़ाइल व्यूज सीधे पोस्टिंग की निरंतरता से जुड़े होते हैं।",
      },
      {
        name: "कंटेंट कैलेंडर",
        icon: <Calendar size={15} />,
        what: "7 दिन पहले तक के टॉपिक्स और फॉर्मेट्स की योजना बनाने की सुविधा।",
        how: "ग्रोथ डैशबोर्ड → Content Calendar। किसी भी दिन पर क्लिक करके टॉपिक बदलें और 'Generate' पर क्लिक करें।",
        tip: "सप्ताहांत पर योजना बनाएं, पूरे सप्ताह की पोस्टिंग ऑटो-पायलट पर।",
      },
    ],
  },
  {
    id: "reminders",
    icon: <Bell size={15} />,
    color: "text-rose-600 bg-rose-50 border-rose-200",
    title: "रिमाइंडर और अलर्ट्स",
    subtitle: "पोस्ट करना कभी न भूलें",
    features: [
      {
        name: "दैनिक ईमेल रिमाइंडर",
        icon: <Mail size={13} />,
        what: "सबसे अच्छे पोस्टिंग समय पर ईमेल भेजता है — पोस्ट प्रीव्यू और डायरेक्ट ऐप लिंक के साथ।",
        how: "Settings → ईमेल पता डालें, समय सेट करें और सक्षम करें। एक बार ईमेल सत्यापित करें।",
        tip: "मंगलवार से गुरुवार सुबह 8-9 बजे (IST) पब्लिश करने का सर्वोत्तम समय है।",
      },
      {
        name: "स्ट्रिक अलर्ट",
        icon: <Bell size={13} />,
        what: "शाम 7:30 बजे (IST) चेक करता है — यदि आज पोस्ट नहीं किया है तो ईमेल अलर्ट भेजता है।",
        how: "जब रिमाइंडर सक्षम हो और स्ट्रिक ≥ 1 दिन हो तो ऑटोमैटिक काम करता है।",
        tip: "केवल 2 घंटे शेष रहने पर ईमेल अलर्ट लाल रंग में बदल जाता है।",
      },
      {
        name: "पुश नोटिफिकेशन",
        icon: <Bell size={13} />,
        what: "ट्रेंडिंग टॉपिक्स, पब्लिश्ड पोस्ट और स्ट्रिक अलर्ट के लिए ब्राउज़र पुश नोटिफिकेशन।",
        how: "Settings → पुश नोटिफिकेशन सक्षम करें और ब्राउज़र अनुमति दें।",
        tip: "विश्वसनीय रिमाइंडर्स के लिए ईमेल और पुश दोनों चालू रखें।",
      },
      {
        name: "इन-ऐप नोटिफिकेशन",
        icon: <Bell size={13} />,
        what: "टॉप नेविगेशन बार में घंटी (Bell) आइकन — सभी गतिविधियों की सूचनाएं एक जगह।",
        how: "घंटी पर क्लिक करें या नोटिफिकेशन पेज पर पूरी हिस्ट्री देखें।",
        tip: "ये सूचनाएं रियल-टाइम (SSE) से आती हैं।",
      },
    ],
  },
  {
    id: "profile",
    icon: <Users size={15} />,
    color: "text-sky-600 bg-sky-50 border-sky-200",
    title: "प्रोफ़ाइल और एसईओ",
    subtitle: "रिक्रूटर्स और नए अवसरों के लिए खोज योग्य बनें",
    features: [
      {
        name: "लिंक्डइन प्रोफ़ाइल एसईओ ऑडिटर",
        icon: <Search size={13} />,
        what: "आपकी लिंक्डइन हेडलाइन, अबाउट सेक्शन और स्किल्स को रिक्रूटर सर्च पैटर्न के अनुसार ऑडिट करता है और ऑप्टिमाइज्ड वर्शन्स सुझाता है।",
        how: "बायें साइडबार → 'Profile SEO Auditor'। अपने वर्तमान विवरण डालें और ऑडिट चलाएं।",
        tip: "ऑप्टिमाइज्ड प्रोफ़ाइल को 40% अधिक व्यूज और 36 गुना अधिक रिक्रूटर संदेश मिलते हैं।",
      },
      {
        name: "प्रोफ़ाइल संपादित करें",
        icon: <Settings size={13} />,
        what: "ऐप में डेवलपर प्रोफ़ाइल अपडेट करें — यह एआई पोस्ट जनरेशन का मुख्य इनपुट है।",
        how: "बायें साइडबार में प्रोफ़ाइल कार्ड पर 'Edit' पर क्लिक करें और विवरण भरें।",
        tip: "अपनी सभी तकनीकों को स्टैक में जोड़ें ताकि जेमिनी उन्हें पोस्ट में शामिल कर सके।",
      },
    ],
  },
  {
    id: "settings",
    icon: <Settings size={15} />,
    color: "text-gray-600 bg-gray-50 border-gray-200",
    title: "सेटिंग्स और खाता",
    subtitle: "ऐप को अपनी पसंद के अनुसार कॉन्फ़िगर करें",
    features: [
      {
        name: "सेटिंग्स पैनल",
        icon: <Settings size={13} />,
        what: "रिमाइंडर समय, ईमेल, पुश नोटिफिकेशन और टॉपिक फिल्टर सेट करने की सुविधा देता है।",
        how: "टॉप नेविगेशन बार या दाएँ साइडबार में सेटिंग्स लिंक पर क्लिक करें।",
        tip: "टॉपिक फिल्टर से तय करें कि ट्रेंडिंग स्कैनर कौन से विषय (React, Node, DevOps आदि) ट्रैक करे।",
      },
      {
        name: "प्रो अपग्रेड (Razorpay)",
        icon: <Shield size={13} />,
        what: "फ्री प्लान में प्रतिदिन 5 पोस्ट की सीमा है। प्रो में असीमित पोस्ट और सभी प्रीमियम फीचर्स मिलते हैं।",
        how: "टॉप बार में 'Upgrade' पर क्लिक करें या पेमेंट पॉपअप खोलने के लिए लिमिट हिट करें।",
        tip: "सीमाएं चालू करने के लिए अपनी .env फ़ाइल में NEXT_PUBLIC_ENABLE_MONETIZATION=true सेट करें।",
      },
    ],
  },
];

// ── UI Translations ─────────────────────────────────────────────────────────
export const UI_TRANSLATIONS = {
  en: {
    title: "Project Docs",
    subtitle: "Guide to all features",
    searchPlaceholder: "Search features...",
    noFeatureFound: 'No feature found for "{search}"',
    featuresCount: "features documented",
    close: "Close",
    what: "What it is",
    how: "How to use",
    tip: "💡 Pro tip",
  },
  hi: {
    title: "प्रोजेक्ट गाइड",
    subtitle: "सभी फीचर्स की गाइड",
    searchPlaceholder: "फीचर ढूंढें...",
    noFeatureFound: '"{search}" के लिए कोई फीचर नहीं मिला',
    featuresCount: "फीचर्स प्रलेखित हैं",
    close: "बंद करें",
    what: "यह क्या है",
    how: "कैसे इस्तेमाल करें",
    tip: "💡 प्रो टिप",
  },
};
